#!/usr/bin/env bash
set -g mode-style "fg=#eff1f5,bg=#5c5f77"
set -g message-style "fg=#eff1f5,bg=#5c5f77"
set -g message-command-style "fg=#eff1f5,bg=#5c5f77"
set -g pane-border-style "fg=#9ca0b0"
set -g pane-active-border-style "fg=#1e66f5"
set -g status "on"
set -g status-justify "left"
set -g status-style "fg=#5c5f77,bg=#eff1f5"
set -g status-left-length "100"
set -g status-right-length "100"
set -g status-left-style NONE
set -g status-right-style NONE
set -g status-left "#[fg=#eff1f5,bg=#1e66f5,bold] #S #[fg=#1e66f5,bg=#eff1f5,nobold,nounderscore,noitalics]"
set -g status-right "#[fg=#eff1f5,bg=#eff1f5,nobold,nounderscore,noitalics]#[fg=#1e66f5,bg=#eff1f5] #{prefix_highlight} #[fg=#5c5f77,bg=#eff1f5,nobold,nounderscore,noitalics]#[fg=#eff1f5,bg=#5c5f77] %Y-%m-%d  %I:%M %p #[fg=#1e66f5,bg=#5c5f77,nobold,nounderscore,noitalics]#[fg=#eff1f5,bg=#1e66f5,bold] #h "
setw -g window-status-activity-style "underscore,fg=#8c8fa1,bg=#eff1f5"
setw -g window-status-separator ""
setw -g window-status-style "NONE,fg=#8c8fa1,bg=#eff1f5"
setw -g window-status-format "#[fg=#eff1f5,bg=#eff1f5,nobold,nounderscore,noitalics]#[default] #I  #W #F #[fg=#eff1f5,bg=#eff1f5,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=#eff1f5,bg=#5c5f77,nobold,nounderscore,noitalics]#[fg=#eff1f5,bg=#5c5f77,bold] #I  #W #F #[fg=#5c5f77,bg=#eff1f5,nobold,nounderscore,noitalics]"
